
#:set s dp(150)


<CanvasExemple1>:
    canvas:
        Rectangle:
            pos: self.center_x-s/2, self.center_y-s/2
            size: s, s
        Ellipse:
            pos: 200, 500
            size: s, s/2
        Line:
            points: (0, 0, self.width/4, 100, self.width/2, 0, self.width*3/4, 100, self.width, 0)
            width: 2


<CanvasExemple2>:
    canvas:
        Line:
            points: (0, self.height/2, self.width, self.height/2)
            width: 2
        Line:
            points: (self.width/2, 0, self.width/2,self.height)
            width: 2

<CanvasExemple3>:
    canvas:
        Color:
            rgb: 1, 0, 0, .3
        Line:
            circle: (200, 200, 100) # center_x, center_y, rayon
            width: 2
        Line:
            ellipse: (500, 300, 100, 200)
            width: 4
        Color:
            rgba: 0, 0, 1, 1
        Line:
            rectangle: (800, 100, 300, 200) # x, y, w, h 
            width: 2


<CanvasExemple4>:
    Button:
        pos: 100, 400
        text: "A"
        on_press: root.on_button_a_click()